I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1505, in script
    $ golempulltogether = true
  File "game/script.rpy", line 1505, in <module>
    $ golempulltogether = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1505, in script
    $ golempulltogether = true
  File "E:\GitHub\dancingwithshadows\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\GitHub\dancingwithshadows\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1505, in <module>
    $ golempulltogether = true
NameError: name 'true' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
dancing with shadows draft 1.0
Fri Feb  7 06:31:15 2025
